name: Packit
version: ${project.version}
main: dev.anhcraft.packit.Packit
api-version: "1.13"
depend: [CraftKit]
authors: [anhcraft]
description: ${project.description}
website: https://anhcraft.dev/
commands:
  packit:
    aliases:
      - pi
      - pack
    description: packit command
